---
- hosts: leafs_DC1, leafs_DC2
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay.yml"
      name: underlay
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/leafs.j2"
      dest: "{{lookup('env','PWD')}}/configs/leafs_{{inventory_hostname}}.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/leafs_{{inventory_hostname}}.cfg"